version: "3"
services:
  embc-api:
    build:
      context: .
      dockerfile: embc-app/Dockerfile
    container_name: embc-api
    image: embc-api
    ports:
      - "5000:5000"
    depends_on:
      - embc-database
    volumes:
      - ./embc-app:/app/embc-app
    environment:
      - SKIP_ANGULAR_BUILD=true
      - ASPNETCORE_ENVIRONMENT=Production
      - BASE_PATH=/embc
      - SITEMINDER_LOGOUT_URL=https://logon.gov.bc.ca/clp-cgi/logoff.cgi
      - DATABASE_SERVICE_NAME=embc-database
      - DB_DATABASE=ess
      - DB_ADMIN_PASSWORD=Test@123
      - DB_USER=ess
      - DB_PASSWORD=embcess@123
  embc-database:
    build:
      context: ./sql-server
      dockerfile: Dockerfile.centos
    image: embc-database
    container_name: embc-database
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - db_volume:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test@123
volumes:
  db_volume:
