version: "3"
services:
  embc-database:
    build:
      context: .
      dockerfile: Dockerfile.centos
    image: embc-database
    container_name: embc-database
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test@123
